config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tours do
    resources :bookings, only: [:index, :create, :update]
    resources :reviews, only: :create
  end

  resources :bookings, only: [ :index, :edit, :update, :destroy ]

  get '/profile', to: 'profiles#index'

end

# /tours => See all tours
# /tours/:id => See details of a particular tour
# /tours/new => Create a new tour
# /tours/bookings => See all bookings for your your (if you are the tour owner)
# /bookings => See all your bookings (be able to update no. of guests, or delete it), and tours you've created

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tour
  validates :content, length: { minimum: 20 }
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, length: { minimum: 200, maximum: 2000 }, allow_blank: false
  validates :price, presence: true, numericality: { only_integer: true }
  validates :date, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true }


  mount_uploader :photo, PhotoUploader

  Categories = ['History', 'Food', 'Adventure', 'Supernatural', 'Sightseeing', 'Romance', 'Adrenaline']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tours, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booked_tours, through: :bookings, source: :tour
  # We create a has many through relationship, linking the booked tours for a user, through the bookings table.


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :create ] #TODO: What other authorizations?
  before_action :set_booking, only: [:edit, :update, :destroy]
  before_action :set_tour, only: [:new, :create]

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    #TODO: If there is already a booking for that particular tour, then update that tour booking, not create a new booking.
    @booking.tour = @tour
    @booking.user = current_user
    if @booking.save
      redirect_to profile_path(just_booked: "true")
    else
      render :new
    end
    authorize @booking
  end

  def edit

  end

  def update
    @booking.update(booking_params)
    redirect_to profile_path(just_booked: "true")
  end

  def destroy
    @booking.destroy
    redirect_to profile_path(just_booked: "true")
  end

  private

  def booking_params
    params.require(:booking).permit(:id, :tour_id, :user_id, :guests)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def set_tour
    @tour = Tour.find(params[:tour_id])
    authorize @tour
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
    @bookings = policy_scope(Booking)
    @my_bookings = @bookings.where(user_id: current_user).order(created_at: :desc)

    @tours = policy_scope(Tour)
    @my_tours = @tours.where(user_id: current_user).order(created_at: :desc)

    @just_booked = params[:just_booked] == "true"
    @just_tours = params[:just_tours] == "true"
  end

  private
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :create ]
  before_action :set_tour, only: [:new, :create]

  def create
    @review = Review.new(review_params)
    @review.tour = @tour
    @review.save

    authorize @review
  end

  private

   def set_tour
    @tour = Tour.find(params[:tour_id])
    authorize @tour
  end

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:my_tours, :show, :edit, :update, :destroy]
  # before_action :set_tour, only: [:create, :show]

  def index
    @tours = policy_scope(Tour)

    if params[:query].present?
      sql_query = "title ILIKE :query OR location ILIKE :query OR category ILIKE :query"
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%").where.not(latitude: nil, longitude: nil)
    else
      @tours = Tour.all.where.not(latitude: nil, longitude: nil)
    end


    @markers = @tours.map do |tour|
      {
        lng: tour.longitude,
        lat: tour.latitude,
        infoWindow: render_to_string(partial: "/shared/map_info", locals: { tour: tour })
      }
    end

    # @all_tours.each do |tour|
    #   if !@categories.include?(tour.category)
    #     @categories << tour.category
    #   end
    # end

  end

  def my_tours
    @my_tours = @tours.where(user_id: current_user)
  end

  def show
    #set_tour method called
    #authorize @tour
    @review = Review.new

    @marker = [{
      lng: @tour.longitude,
      lat: @tour.latitude,
    }]
    @booking = Booking.new

    if current_user != nil
      @booked = current_user.booked_tours.include?(@tour)
    end

    if @booked
      @booking = current_user.bookings.where(tour_id: params[:id]).first
    end

    authorize @booking
  end

  def new
    @tour = Tour.new
    authorize @tour
  end

  def create
    @tour = Tour.new(tour_params)
    authorize @tour
    @tour.user = current_user
    @tour.save
    if @tour.save
      redirect_to tour_path(@tour)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @tour.update(tour_params)
    redirect_to tour_path(@tour)
  end

  def destroy
    @tour.destroy
    redirect_to profile_path(just_tours: "true")
  end

  private


  def set_tour
    @tour = Tour.find(params[:id])
    authorize @tour
  end

  def tour_params
    params.require(:tour).permit(:title, :location, :description, :price, :photo, :date, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h2>My bookings</h2>
<% @bookings.each do |booking| %>
  <% this_booking = booking.tour %>
  <h4><%= link_to this_booking.title, tour_path(this_booking.id) %></h4>
  <p><%= this_booking.description %> in <%= this_booking.location %></p>
  <p>No. of guests booked: <%= booking.guests %></p>
  <h6><%= link_to "Delete booking", booking_path(booking.id), method: :delete %></h4>
  <p>Update the number of guests?</p>
        <%= simple_form_for booking do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.select :guests, options_for_select(1..10) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit %>
          </div>
        <% end %>
<% end %>

app/views/bookings/new.html.erb
<%= simple_form_for [@tour, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AirTours | Best Tours in the World</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <div class="banner-content-home">
          <br><br><br><br><br><br>
          <p>Dare to explore</p>
          <br>
          <a class="btn-ghost" href='<%= tours_path%>'>Begin</a>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/profiles/index.html.erb
<div class="container">
  <h1>My Tours / Bookings</h1>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item <%= 'active' unless @just_booked %>">
      <a class="nav-link <%= 'active' unless @just_booked %>" id="home-tab" data-toggle="tab" href="#Tours" role="tab" aria-controls="home" aria-selected="true">My Tours (<%= @my_tours.count%>)</a>
    </li>
    <li class="nav-item <%= 'active' if @just_booked %>">
      <a class="nav-link <%= 'active' if @just_booked %>" id="profile-tab" data-toggle="tab" href="#Bookings" role="tab" aria-controls="profile" aria-selected="false">My Bookings (<%= @my_bookings.count%>)</a>
    </li>
  </ul>

  <div class="tab-content" id="tab-profile-content">
    <div class="tab-pane fade in <%= 'active' unless @just_booked %>" id="Tours">
      <h4><strong>My Tours:  <%= @my_tours.count%> in total </strong></h4>
      <div class="container">
        <% @my_tours.each do |tour| %>
        <% people_sum = tour.bookings.map(&:guests).sum %>
        <div class="row">
          <div class="big-card">
            <div class="big-card-image-container">
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path tour.photo, height: 150, width: 200, crop: :fill %>)">
                <!-- <h4><%= link_to tour.title, tour_path(tour) %> </h4> -->
                <h5><%= tour.location %></h5>
              </div>
              <div class="big-card-bottom-card">
                <p><i class="fas fa-clock">&nbsp;</i><%= rand(1..3) %> hours</p>
                <p><i class="fas fa-dollar-sign">&nbsp;</i><%= tour.price %></p>
              </div>
              <div class="big-card-links">
                    <p><%= link_to "Edit", edit_tour_path(tour) %></p>
                    <p><%= link_to "Delete", tour_path(tour), method: :delete %></p>
              </div>

            </div>
            <div class="big-card-details">
              <div class="big-card-main-details">
                <h3><%= link_to tour.title, tour_path(tour) %></h3>


                <p><i class="fas fa-map-marker-alt">&nbsp;</i><%= tour.location.capitalize %></p>
                <p><i class="fas fa-table">&nbsp;</i><%= tour.date %></p>

                <p><i class="fas fa-users"></i> <%= pluralize people_sum, 'person' %></p>
                <p>Capacity: <%= tour.capacity %></p>
                <h4>Your earnings:   $<%= tour.price*people_sum %></h4>
              </div>

              <!-- <div class="big-card-price">
              </div> -->
            </div>
          </div>
        </div>
        <% end %>
          <%#= link_to 'Delete tour', tour_path(@tour), method: :delete #TODO: Create an alert that tells your that 'tour_name' has been deleted %>
          <%#= link_to 'Edit tour', tour_path(@tour), method: :delete #TODO: Create an alert that tells your that 'tour_name' has been deleted %>

      </div>
    </div>


    <div class="tab-pane fade in <%= 'active' if @just_booked %> " id="Bookings">
      <h4><strong>My Bookings:  <%= @my_bookings.count%> in total </strong></h4>
      <div class="container">
        <% @my_bookings.each do |booking| %>
        <% tour = booking.tour %>
        <div class="row">
          <div class="big-card">
            <div class="big-card-image-container">

              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path tour.photo, height: 150, width: 200, crop: :fill %>)">
                <h5><%= tour.location %></h5>
              </div>
              <div class="big-card-bottom-card">
                <p><i class="fas fa-clock">&nbsp;</i><%= rand(1..3) %> hours</p>
                <p><i class="fas fa-dollar-sign">&nbsp;</i><%= tour.price %></p>
              </div>
              <div class="big-card-links">
                <p><%= link_to "Delete", booking_path(booking), method: :delete %></p>
              </div>
            </div>
            <div class="big-card-details">

              <div class="big-card-main-details">
                <h3><%= link_to tour.title, tour_path(tour) %></h3>
                <p><i class="fas fa-map-marker-alt">&nbsp;</i><%= tour.location.capitalize %></p>
                <p><i class="fas fa-table">&nbsp;</i><%= tour.date %></p>
                <p><i class="fas fa-users"> </i> Booked:     <strong><%= booking.guests %></strong>
                <h4> Total Cost: <i class="fas fa-dollar-sign"></i><%= tour.price*booking.guests %> </h4>




                <p>Update # of guests:</p>
                  <%= simple_form_for booking do |f| %>
                  <div id="form-guest-update">
                    <%= f.error_notification %>
                    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                    <div class="form-inputs">
                      <%= f.select :guests, options_for_select(1..10) %>
                    </div>
                    <div class="form-actions">
                      <%= f.button :submit %>
                    </div>
                  <% end %>
                </div>
              </div>

              <!-- <div class="big-card-bookings">
              </div> -->
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ @tour, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/create.js.erb
var newReview = '<p><%= @review.content %></p>'


var reviews = document.querySelector('.reviews')

reviews.insertAdjacentHTML('beforeend', newReview)

var inputBox = document.querySelector('review_content')
inputBox.value = ""

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Developed by the best team
  </div>
</div>

app/views/shared/_map_info.html.erb
<h5 style="font-size: 10px;"><%=tour.title%></h5>
      <br>

      <p><i class="fas fa-map-marker-alt">&nbsp;</i><%= tour.location.capitalize %></p>
      <p><i class="fas fa-table">&nbsp;</i><%= tour.date %></p>
      <p><i class="fas fa-clock">&nbsp;</i><%= rand(1..3) %> hours</p>
      <p><i class="fas fa-dollar-sign">&nbsp;</i><%= tour.price %></p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
    <div id="company-name">AirTours</div>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "See all tours", tours_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create a tour", new_tour_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://avatars1.githubusercontent.com/u/26271696?s=400&u=8c22b28b3a92cce0658876ef47ffd7a67e402e7c&v=4", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My Tours / Bookings") %>
              <% end %>
            </li>
            <!-- <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Profile") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>

        <!-- Links when logged in -->
        <li><%= link_to "See all tours", tours_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Create a tour", new_tour_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to profile_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "My Tours / Bookings") %>
              <% end %>
        </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
        <% else %>
          <li><%= link_to "See all tours", tours_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>
        <% end %>
      </ul>
    </div>
  </div>
</div>
        <!-- Login link (when logged out) -->

app/views/tours/edit.html.erb
<div class="container">
  <div class="row" id="form-create">
    <h2>Edit Tour</h2>

        <%= simple_form_for(@tour) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :title %>
          <%= f.input :location %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :date %>
          <%= f.input :capacity %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>
        <div class="form-actions">
          <%= f.button :submit %>
          <% end %>
</div>
</div>

app/views/tours/index.html.erb
<div class="container-fluid">
  <div class="search-container">
    <h3>All tours</h3>
    <%= form_tag tours_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        id: "search-bar",
      placeholder: "Find a tour near you"
      %>
    <% end %>
  </div>

  <div class="container-fluid margin-bottom">
    <h1 class="text-center mb-3">Types of tours</h1><br>
    <div id="tourCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner row w-100 mx-auto">
        <% counter = 0 %>
        <% Tour::Categories.each do |category| %>

          <div class="carousel-item col-md-3 <%= 'active' if counter == 0 %>">
            <div class="card">
              <!-- <img class="card-img-top img-fluid" src="http://placehold.it/800x600/f44242/fff" alt="Card image cap"> -->
              <div class="card-body" style="background-color: #F3E0DC">
                <h4 class="card-title"><%= link_to category.upcase, tours_path(query: category) %></h4>

                <!-- <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
              </div>
            </div>
          </div>
          <% counter += 1 %>
        <% end %>

      </div>
      <a class="carousel-control-prev" href="#tourCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only arrow">Previous</span>
      </a>
      <a class="carousel-control-next" href="#tourCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only arrow">Next</span>
      </a>
    </div>
  </div>

  <br><br><br>

  <div class="layout-container">
    <div class="container">
      <div class="row">
        <% @tours.each do |tour| %>
        <div class="col-xs-12 col-md-6 col-lg-4">
          <div class="card">
            <img class="card-img-top img-fluid" src="<%= cl_image_path tour.photo%>" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title"><%= link_to tour.title, tour_path(tour) %></h4>
              <div class="card-text">
              <p><i class="fas fa-table">&nbsp;</i><%= tour.date %>&nbsp;
              &nbsp;<i class="fas fa-clock">&nbsp;</i><%= rand(1..3) %> hours
              &nbsp;<i class="fas fa-dollar-sign">&nbsp;</i><%= tour.price %></p>
              <% desc = tour.description[0,200] +"..."%>
              <p><%= desc %></p>

              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>



    <div
      class="index-map" id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
  $("#tourCarousel").on("slide.bs.carousel", function(e) {
    var $e = $(e.relatedTarget);
    var idx = $e.index();
    var itemsPerSlide = 4;
    var totalItems = $(".carousel-item").length;

    if (idx >= totalItems - (itemsPerSlide - 1)) {
      var it = itemsPerSlide - (totalItems - idx);
      for (var i = 0; i < it; i++) {
        // append slides to end
        if (e.direction == "left") {
          $(".carousel-item")
            .eq(i)
            .appendTo(".carousel-inner");
        } else {
          $(".carousel-item")
            .eq(0)
            .appendTo($(this).find(".carousel-inner"));
        }
      }
    }
  });
});

</script>

app/views/tours/new.html.erb
<!-- TODO: Add date selector, add ability to add photo -->


<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Create new tour
</button> -->

<!-- Modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">tour details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> -->

<div class="container">
  <div class="row" id="form-create">
    <div class="col-xs-3"></div>
    <div class="col-xs-12 col-sm-6 sol-lg4">

      <%= simple_form_for(@tour) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :title %>
        <%= f.input :location %>
        <%= f.input :description %>
        <%= f.input :category, collection: [ "History", "Food", "Adventure", "Supernatural", "Sightseeing", "Romance", "Adrenaline" ] %>
        <%= f.input :price %>
        <%= f.input :date %>
        <%= f.input :capacity %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>
      <%= f.button :submit %>
<!--       </div> -->
   <!--  <div class="modal-footer"> -->
      <!-- <div class="form-actions"> -->
   <!--    </div> -->
    <% end %>
    </div>
  </div>
</div>
<!--       </div>
    </div>
  </div>
</div> -->

app/views/tours/test.html.erb
      <% @tours.each do |tour| %>
      <div class="col-md-3 active">
        <div class="card">
          <img class="card-img-top img-fluid" src="<%= cl_image_path tour.photo%>" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title"><%= link_to tour.title, tour_path(tour) %></h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
    <% end %>



        <div class="layout-container">
    <div class="container">
      <div class="row">





        <div class="col-xs-12 col-sm-6 col-lg-4">
          <div class="cards">
              <div class="card-name"><%= link_to tour.title, tour_path(tour) %></div>
              <h5><%= tour.location %></h5>
              <!-- <p><%= tour.description %> | <%= tour.price %></p> -->
              <!-- <p><%= tour.user_id %> | <%= tour.user %></p> -->
            </div>
          </div>
        </div>
        <% end %>
      </div>
      </div>